/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:0ae9c588-0268-4ecf-bb7d-4e42d0f2574f",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_xozd1lod3",
    "aws_user_pools_web_client_id": "51h7nsc3gkn41o48606monemvm",
    "oauth": {}
};


export default awsmobile;
