export const REMOVE_DOG = "REMOVE_DOG";
export const SET_CURRENT_DOG = "SET_CURRENT_DOG";
export const ADD_DOG = "ADD_DOG";
export const UPDATE_DOGS = "UPDATE_DOGS";

export const UPDATE_EXERCISE = "UPDATE_EXERCISE";
export const REMOVE_EXERCISE = "REMOVE_EXERCISE";
export const SET_CURRENT_EXERCISE = "SET_CURRENT_EXERCISE";
export const ADD_EXERCISE = "ADD_EXERCISE";
export const LOADING = "LOADING";
